#+title: PlotFunction: A C++ graphical program for plotting functions and doing calculus
#+author: Miguel Valbuena


* TABLE OF CONTENTS :toc:
- [[#required-software][Required software]]
  - [[#wxwidgets-libraries][wxWidgets libraries]]
  - [[#libvalmath][libvalmath]]
- [[#features][Features]]
  - [[#plotter][Plotter]]
  - [[#calculus][Calculus]]
  - [[#rational-interpolation][Rational interpolation]]
  - [[#regression][Regression]]
  - [[#export-graphic][Export graphic]]
  - [[#high-customization][High customization]]

* Required software
** wxWidgets libraries
As this program uses the wxWidgets library, ~wx-config~ should be available on your system.
** libvalmath
You can clone the git repository https://github.com/valmig/libvalmath.git and build the library
following the given instructions.

* Features
** Plotter
plotting functions, algebraic curves and more geometric objects like points, lines, polygons, circles, etc...
** Calculus
analyzes functions (definition gaps, zeros, extreme points, inflection points) and computes derivations and
some stammfunctions.
** Rational interpolation
computes the interpolation polynomial to a given set of points.
** Regression
computes the regression polynomial of a given degree to a given set of points.
** Export graphic
you can export your graphic as a png file, or copy/paste it directly into your documents.
** High customization
Great variability for graph colors/width, axis colors, axis range, axis scale, etc..
