#+title: PlotFunction: A C++ graphical program for plotting functions and doing calculus
#+author: Miguel Valbuena


* TABLE OF CONTENTS :toc:
- [[#required-c-libraries][Required C++ libraries]]
  - [[#wxwidgets-libraries][wxWidgets libraries]]
  - [[#libvalmath][libvalmath]]
- [[#features][Features]]
  - [[#plotter][Plotter]]
  - [[#calculus][Calculus]]
  - [[#rational-interpolation][Rational interpolation]]
  - [[#regression][Regression]]
  - [[#export-graphic][Export graphic]]
  - [[#import-graphic][Import graphic]]
  - [[#high-customization][High customization]]
  - [[#support-for-latex][Support for Latex]]

* Required C++ libraries
** wxWidgets libraries
As this program uses the wxWidgets library, ~wx-config~ should be available on your system.
** libvalmath
You can clone the git repository https://github.com/valmig/libvalmath.git and build the library
following the given instructions.

* Features
** Plotter
plotting functions, algebraic curves, parametric curves and more geometric objects like points, lines, polygons, circles, etc...
** Calculus
analyzes functions (definition gaps, zeros, extreme points, inflection points), computes derivations and
some stammfunctions, zero approximation, intersection points of two functions, tangents, normal lines, etc.
** Rational interpolation
computes the interpolation polynomial to a given set of points.
** Regression
computes the regression polynomial of a given degree to a given set of points.
** Export graphic
you can export your graphic as a png file, or copy/paste it directly into your documents.
** Import graphic
you can copy png pictures to the coordinate system.
** High customization
Great variability for graph colors/width, axis colors, axis range, axis scale, etc..
** Support for Latex
(On Gnu-Linux-systems if ~latex~ and ~dvipng~ are installed.)
